# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewFeed' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NewFeed
  pod 'FSImageViewer', '~> 3.4'



  target 'NewFeedTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewFeedUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
